import React, { useState } from 'react';

const PACE_LABELS = { intensive:'Intensive', balanced:'Balanced', relaxed:'Relaxed' };
const PACE_MULT   = { intensive:0.6, balanced:1, relaxed:1.5 };

const PRIORITY_CFG = {
  'High Priority':  { color:'#b91c1c', bg:'#fef2f2', border:'#fecaca', dot:'#dc2626' },
  'Medium Priority':{ color:'#92400e', bg:'#fffbeb', border:'#fde68a', dot:'#d97706' },
  'Good to Have':   { color:'#166534', bg:'#f0fdf4', border:'#bbf7d0', dot:'#16a34a' },
};

const CAT_SHORT = {
  programming_languages:'Lang', web_frameworks:'Framework', databases:'DB',
  cloud_devops:'DevOps', ml_ai:'ML/AI', data_engineering:'Data',
  soft_skills:'Soft Skill', mobile:'Mobile', security:'Sec', testing:'Test', other:'Other'
};

// Render multi-line text with bullet formatting
function FormattedText({ text, fontSize = 12.5 }) {
  if (!text) return null;
  const lines = text.split('\n').filter(l => l.trim());
  return (
    <div style={{ fontSize, lineHeight:1.65 }}>
      {lines.map((line, i) => {
        const isNum    = /^\d+\./.test(line.trim());
        const isBullet = /^[-•]/.test(line.trim());
        if (isNum || isBullet) return (
          <div key={i} style={{ display:'flex', gap:7, marginBottom:3 }}>
            <span style={{ color:'var(--primary)', fontWeight:700, flexShrink:0 }}>
              {isNum ? line.trim().match(/^\d+\./)[0] : '•'}
            </span>
            <span>{isNum ? line.trim().replace(/^\d+\.\s*/,'') : line.trim().replace(/^[-•]\s*/,'')}</span>
          </div>
        );
        return <p key={i} style={{ marginBottom: i < lines.length - 1 ? 5 : 0 }}>{line}</p>;
      })}
    </div>
  );
}

function exportPlan(data, pace, mult) {
  const items  = data.roadmap?.roadmap_items || [];
  const role   = data.target_role || 'target role';
  const score  = data.score_breakdown?.final_score || 0;
  const totalW = Math.round((data.roadmap?.total_weeks || 0) * mult);

  const lines = [];
  lines.push('LEARNING ROADMAP — JobFit AI');
  lines.push('='.repeat(50));
  lines.push(`Target Role : ${role.charAt(0).toUpperCase() + role.slice(1)}`);
  lines.push(`Match Score : ${score}/100`);
  lines.push(`Pace        : ${PACE_LABELS[pace]}`);
  lines.push(`Total Time  : ~${totalW} weeks`);
  lines.push(`Generated   : ${new Date().toLocaleDateString('en-IN')}`);
  lines.push('');

  const phases = data.roadmap?.phases || [];
  for (const phase of phases) {
    if (!phase.items.length) continue;
    lines.push('-'.repeat(50));
    lines.push(phase.phase.toUpperCase());
    lines.push(phase.description);
    lines.push('');
    const phaseItems = items.filter(it => phase.items.includes(it.skill));
    for (const item of phaseItems) {
      lines.push(`  [${item.priority_label.toUpperCase()}] ${item.skill.toUpperCase()}`);
      lines.push(`  Category : ${CAT_SHORT[item.category] || item.category}`);
      lines.push(`  Time     : ~${Math.round(item.weeks_to_learn * mult)} weeks`);
      if (item.reason) {
        lines.push(`  Why      : ${item.reason.split('\n')[0].slice(0, 120)}`);
      }
      if (item.resources?.length) {
        lines.push('  Resources:');
        for (const r of item.resources) {
          lines.push(`    - ${r.title}`);
          lines.push(`      ${r.url}`);
        }
      }
      lines.push('');
    }
  }

  lines.push('='.repeat(50));
  lines.push('Gap Summary');
  lines.push(`  Hard Gaps       : ${data.gap_analysis?.summary?.hard_gap_count || 0}`);
  lines.push(`  Transferable    : ${data.gap_analysis?.summary?.transferable_count || 0}`);
  lines.push(`  Matched Skills  : ${data.gap_analysis?.summary?.match_count || 0}`);
  lines.push('');
  lines.push('Generated by JobFit AI Resume Analyzer');

  const blob = new Blob([lines.join('\n')], { type:'text/plain' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `learning_roadmap_${role.replace(/\s+/g,'_')}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function LearningPlan({ data }) {
  const [pace, setPace] = useState('balanced');
  const [done, setDone] = useState([]);
  const roadmap = data.roadmap || {};
  const items   = roadmap.roadmap_items || [];
  const phases  = roadmap.phases || [];
  const mult    = PACE_MULT[pace];

  const topQuickStart = items.filter(i => i.priority_label === 'High Priority').slice(0, 3);
  const totalWeeks    = Math.round((roadmap.total_weeks || 0) * mult);

  function toggleDone(skill) {
    setDone(prev => prev.includes(skill) ? prev.filter(s => s !== skill) : [...prev, skill]);
  }

  if (items.length === 0) {
    return (
      <div className="fade-in" style={{ maxWidth:960, margin:'0 auto' }}>
        <h1 style={{ fontSize:26, fontWeight:800, marginBottom:12 }}>Learning Roadmap</h1>
        <div className="card" style={{ textAlign:'center', padding:'60px', color:'var(--gray-400)' }}>
          <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="var(--success)" strokeWidth="2" strokeLinecap="round" style={{ margin:'0 auto 16px', display:'block' }}><polyline points="20 6 9 17 4 12"/></svg>
          <p style={{ fontWeight:700, color:'var(--success)', fontSize:16 }}>No gaps to close!</p>
          <p style={{ marginTop:6, fontSize:13 }}>Your resume is already a strong match for this role.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="fade-in" style={{ maxWidth:960, margin:'0 auto' }}>
      {/* Header */}
      <div style={{ marginBottom:28 }}>
        <div style={{ display:'flex', alignItems:'center', gap:8, marginBottom:6 }}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--success)" strokeWidth="2.5" strokeLinecap="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>
          <span style={{ fontSize:12, fontWeight:700, color:'var(--success)', textTransform:'uppercase', letterSpacing:'0.06em' }}>Personalized Growth Path</span>
        </div>
        <div style={{ display:'flex', alignItems:'flex-start', justifyContent:'space-between', flexWrap:'wrap', gap:16 }}>
          <div>
            <h1 style={{ fontSize:26, fontWeight:800, marginBottom:4 }}>Learning Roadmap</h1>
            <p style={{ color:'var(--gray-500)', fontSize:13.5 }}>
              Structured based on the most critical gaps identified between your resume and the{' '}
              <strong style={{ color:'var(--gray-700)' }}>
                {data.target_role ? data.target_role.charAt(0).toUpperCase() + data.target_role.slice(1) : 'target role'}
              </strong>.
            </p>
          </div>
          <div style={{ display:'flex', alignItems:'center', gap:12, flexWrap:'wrap' }}>
            {/* Pace selector */}
            <div style={{ display:'flex', background:'var(--gray-100)', padding:4, borderRadius:'var(--radius)', gap:2 }}>
              {Object.keys(PACE_LABELS).map(p => (
                <button key={p} onClick={() => setPace(p)} style={{
                  padding:'6px 14px', border:'none', borderRadius:7, cursor:'pointer',
                  fontFamily:'inherit', fontSize:12, fontWeight:600, transition:'all 0.15s',
                  background: pace === p ? '#fff' : 'transparent',
                  color: pace === p ? 'var(--primary)' : 'var(--gray-500)',
                  boxShadow: pace === p ? 'var(--shadow)' : 'none'
                }}>
                  {PACE_LABELS[p]}
                </button>
              ))}
            </div>
            {/* Working export button */}
            <button
              className="btn btn-secondary btn-sm"
              onClick={() => exportPlan(data, pace, mult)}
              title="Download roadmap as text file"
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
              Export Plan
            </button>
          </div>
        </div>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'1fr 280px', gap:24 }}>
        {/* Main timeline */}
        <div>
          <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:20 }}>
            <div style={{ display:'flex', alignItems:'center', gap:8 }}>
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="2" strokeLinecap="round"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg>
              <h2 style={{ fontSize:16, fontWeight:700 }}>Timeline Overview</h2>
            </div>
            <div style={{ display:'flex', gap:14, fontSize:12 }}>
              <div style={{ display:'flex', alignItems:'center', gap:5, color:'var(--primary)' }}>
                <div style={{ width:8, height:8, borderRadius:'50%', background:'var(--primary)' }} />
                In Progress
              </div>
              <div style={{ display:'flex', alignItems:'center', gap:5, color:'var(--gray-400)' }}>
                <div style={{ width:8, height:8, borderRadius:'50%', background:'var(--gray-300)' }} />
                Not Started
              </div>
            </div>
          </div>

          {phases.filter(p => p.items.length > 0).map((phase, pi) => {
            const phaseItems = items.filter(it => phase.items.includes(it.skill));
            const phaseWeeks = Math.round(phaseItems.reduce((s, i) => s + i.weeks_to_learn, 0) * mult);
            const phaseColors = ['var(--primary)', '#0e7490', 'var(--purple)'];
            const phaseLabel  = phase.phase.split(' - ')[1] || phase.phase;

            return (
              <div key={pi} style={{ marginBottom:32 }}>
                <div style={{ display:'flex', alignItems:'flex-start', gap:14, marginBottom:16 }}>
                  <div style={{
                    width:36, height:36, borderRadius:'50%',
                    background: phaseColors[pi] || 'var(--gray-400)', color:'#fff',
                    display:'flex', alignItems:'center', justifyContent:'center',
                    fontWeight:800, fontSize:15, flexShrink:0
                  }}>{pi + 1}</div>
                  <div style={{ flex:1 }}>
                    <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:3 }}>
                      <h3 style={{ fontWeight:700, fontSize:15 }}>{phaseLabel}</h3>
                      <div style={{
                        display:'flex', alignItems:'center', gap:5,
                        background:'var(--gray-100)', borderRadius:99, padding:'3px 10px',
                        fontSize:11, fontWeight:600, color:'var(--gray-500)'
                      }}>
                        <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                        ~{phaseWeeks} weeks
                      </div>
                    </div>
                    <p style={{ fontSize:12.5, color:'var(--gray-500)' }}>{phase.description}</p>
                  </div>
                </div>

                <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:14, paddingLeft:50 }}>
                  {phaseItems.map(item => (
                    <RoadmapCard
                      key={item.skill} item={item} pace={mult}
                      done={done.includes(item.skill)}
                      onToggle={() => toggleDone(item.skill)}
                    />
                  ))}
                </div>
              </div>
            );
          })}
        </div>

        {/* Right sidebar */}
        <div style={{ display:'flex', flexDirection:'column', gap:16 }}>
          {/* Quick start */}
          {topQuickStart.length > 0 && (
            <div className="card" style={{ padding:'18px' }}>
              <div style={{ display:'flex', alignItems:'center', gap:7, marginBottom:6 }}>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--warning)" strokeWidth="2.5" strokeLinecap="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>
                <h3 style={{ fontSize:13, fontWeight:700 }}>High-Impact Quick Start</h3>
              </div>
              <p style={{ fontSize:12, color:'var(--gray-400)', marginBottom:14 }}>Start here to bridge the largest score gaps first.</p>
              {topQuickStart.map((item, i) => (
                <div key={item.skill} style={{
                  display:'flex', alignItems:'center', gap:10, padding:'10px 0',
                  borderBottom: i < topQuickStart.length - 1 ? '1px solid var(--gray-100)' : 'none'
                }}>
                  <div style={{
                    width:24, height:24, borderRadius:'50%', background:'var(--gray-100)',
                    display:'flex', alignItems:'center', justifyContent:'center',
                    fontSize:10, fontWeight:800, color:'var(--gray-500)', flexShrink:0
                  }}>
                    {String(i + 1).padStart(2, '0')}
                  </div>
                  <div style={{ flex:1, minWidth:0 }}>
                    <div style={{ fontWeight:600, fontSize:13, textTransform:'capitalize', marginBottom:1 }}>{item.skill}</div>
                    <div style={{ fontSize:10, fontWeight:700, textTransform:'uppercase', color:'var(--danger)', letterSpacing:'0.05em' }}>CRITICAL</div>
                  </div>
                  <div style={{ fontSize:12, fontWeight:700, color:'var(--success)', flexShrink:0 }}>
                    +{Math.round(item.severity * 1.5)}% Score
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Success stats */}
          <div className="card" style={{ padding:'18px' }}>
            <h3 style={{ fontSize:13, fontWeight:700, marginBottom:14 }}>Success Stats</h3>
            <div style={{ marginBottom:12 }}>
              <div style={{ display:'flex', justifyContent:'space-between', fontSize:12, marginBottom:5 }}>
                <span style={{ color:'var(--gray-500)' }}>Path Completion</span>
                <span style={{ fontWeight:700 }}>
                  {items.length > 0 ? Math.round(done.length / items.length * 100) : 0}%
                </span>
              </div>
              <div className="progress-track">
                <div className="progress-fill" style={{
                  width: items.length > 0 ? (done.length / items.length * 100) + '%' : '0%',
                  background:'var(--primary)'
                }} />
              </div>
            </div>
            <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:10 }}>
              <div style={{ textAlign:'center', padding:'12px', background:'var(--primary-light)', borderRadius:'var(--radius)' }}>
                <div style={{ fontSize:24, fontWeight:800, color:'var(--primary)' }}>{done.length}</div>
                <div style={{ fontSize:11, color:'var(--gray-400)' }}>Skills Learned</div>
              </div>
              <div style={{ textAlign:'center', padding:'12px', background:'var(--gray-50)', borderRadius:'var(--radius)', border:'1px solid var(--gray-200)' }}>
                <div style={{ fontSize:24, fontWeight:800, color:'var(--gray-700)' }}>{items.length - done.length}</div>
                <div style={{ fontSize:11, color:'var(--gray-400)' }}>Remaining</div>
              </div>
            </div>
          </div>

          {/* AI recommendation */}
          <div className="card" style={{ padding:'18px', background:'linear-gradient(135deg,var(--primary-light),var(--accent-light))', border:'1px solid var(--primary-mid)' }}>
            <div style={{ display:'flex', alignItems:'center', gap:7, marginBottom:8 }}>
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--primary)" strokeWidth="2.5" strokeLinecap="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>
              <h3 style={{ fontSize:13, fontWeight:700, color:'var(--primary)' }}>AI Recommendation</h3>
            </div>
            <p style={{ fontSize:12, color:'#1e40af', lineHeight:1.65 }}>
              Candidates who complete the high-priority skills first have a{' '}
              <strong>40% higher chance</strong> of passing the initial technical screening for this role.
            </p>
            <button className="btn btn-primary btn-sm" style={{ marginTop:12, width:'100%', justifyContent:'center' }}>
              See Hiring Insights
            </button>
          </div>

          {/* Set reminder */}
          <div style={{ textAlign:'center', padding:'16px', background:'#fff', border:'1px solid var(--gray-200)', borderRadius:'var(--radius-lg)' }}>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--gray-300)" strokeWidth="1.5" strokeLinecap="round" style={{ margin:'0 auto 8px', display:'block' }}><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>
            <p style={{ fontWeight:700, fontSize:13, marginBottom:4 }}>Want a Review?</p>
            <p style={{ fontSize:12, color:'var(--gray-400)', marginBottom:12 }}>
              After completing Phase 1, we recommend re-running the analysis.
            </p>
            <button className="btn btn-outline btn-sm" style={{ width:'100%', justifyContent:'center' }}>
              Set Reminder
            </button>
          </div>

          {/* Total time card */}
          <div style={{ padding:'16px 18px', background:'var(--gray-800)', borderRadius:'var(--radius-lg)', color:'#fff' }}>
            <div style={{ fontSize:11, color:'var(--gray-400)', marginBottom:4 }}>Estimated total time</div>
            <div style={{ fontSize:26, fontWeight:800, marginBottom:2 }}>{totalWeeks} weeks</div>
            <div style={{ fontSize:11, color:'var(--gray-400)' }}>at {PACE_LABELS[pace].toLowerCase()} pace</div>
          </div>
        </div>
      </div>
    </div>
  );
}

function RoadmapCard({ item, pace, done, onToggle }) {
  const [open, setOpen] = useState(false);
  const cfg   = PRIORITY_CFG[item.priority_label] || PRIORITY_CFG['Good to Have'];
  const weeks = Math.round(item.weeks_to_learn * pace);
  const isSoft = item.category === 'soft_skills';

  return (
    <div style={{
      background: done ? 'var(--success-light)' : '#fff',
      border: `1px solid ${done ? 'var(--success-mid)' : 'var(--gray-200)'}`,
      borderRadius:'var(--radius-lg)', padding:'16px',
      opacity: done ? 0.8 : 1, transition:'all 0.2s'
    }}>
      {/* Header */}
      <div style={{ display:'flex', alignItems:'flex-start', gap:8, marginBottom:10 }}>
        <div style={{ flex:1, minWidth:0 }}>
          <div style={{ display:'flex', alignItems:'center', gap:6, flexWrap:'wrap', marginBottom:6 }}>
            <h3 style={{
              fontWeight:700, fontSize:14, textTransform:'capitalize',
              textDecoration: done ? 'line-through' : 'none',
              color: done ? 'var(--gray-400)' : 'var(--gray-900)'
            }}>
              {item.skill}
            </h3>
            <span style={{ background:cfg.bg, color:cfg.color, border:`1px solid ${cfg.border}`, borderRadius:99, fontSize:10, fontWeight:700, padding:'2px 8px' }}>
              {item.priority_label}
            </span>
            {isSoft && (
              <span style={{ background:'#f0fdf4', color:'#166534', border:'1px solid #bbf7d0', borderRadius:99, fontSize:10, fontWeight:700, padding:'2px 8px' }}>
                Soft Skill
              </span>
            )}
          </div>
          <div style={{ fontSize:12, color:'var(--gray-400)', display:'flex', alignItems:'center', gap:4 }}>
            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
            {isSoft ? `~${weeks} weeks to demonstrate` : `~${weeks} weeks to learn`}
          </div>
        </div>
        {/* Done checkbox */}
        <button onClick={onToggle} style={{
          width:22, height:22, borderRadius:'50%',
          border:`2px solid ${done ? 'var(--success)' : 'var(--gray-300)'}`,
          background: done ? 'var(--success)' : '#fff',
          cursor:'pointer', flexShrink:0,
          display:'flex', alignItems:'center', justifyContent:'center'
        }}>
          {done && <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="3" strokeLinecap="round"><polyline points="20 6 9 17 4 12"/></svg>}
        </button>
      </div>

      {/* Bridge note */}
      {item.transferable_from?.length > 0 && (
        <div style={{ fontSize:12, color:'#92400e', background:'var(--warning-light)', borderRadius:6, padding:'6px 10px', marginBottom:10 }}>
          Bridge: your <strong>{item.transferable_from.join(', ')}</strong> knowledge applies here
        </div>
      )}

      {/* Resources */}
      <div style={{ marginBottom:8 }}>
        <div style={{ fontSize:10, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.06em', color:'var(--gray-400)', marginBottom:6 }}>
          {isSoft ? 'How to demonstrate this' : 'Recommended resources'}
        </div>
        {(item.resources || []).map((res, ri) => (
          <a key={ri} href={res.url} target="_blank" rel="noopener noreferrer" style={{
            display:'flex', alignItems:'center', gap:7, padding:'7px 10px',
            background:'var(--gray-50)', border:'1px solid var(--gray-200)',
            borderRadius:7, marginBottom:5, textDecoration:'none',
            color:'var(--gray-700)', fontSize:12, fontWeight:500, transition:'all 0.15s'
          }}>
            <div style={{
              width:16, height:16, borderRadius:4,
              background: ri === 0 ? (isSoft ? '#dcfce7' : '#fee2e2') : '#f3f4f6',
              display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0
            }}>
              <svg width="9" height="9" viewBox="0 0 24 24" fill="none"
                stroke={ri === 0 ? (isSoft ? '#16a34a' : '#b91c1c') : 'var(--gray-500)'}
                strokeWidth="2.5" strokeLinecap="round">
                {isSoft
                  ? <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/>
                  : <polygon points="5 3 19 12 5 21 5 3"/>
                }
              </svg>
            </div>
            <span style={{ flex:1, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>
              {res.title}
            </span>
            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="var(--gray-300)" strokeWidth="2" strokeLinecap="round"><path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>
          </a>
        ))}
      </div>

      {/* Why learn toggle */}
      <button onClick={() => setOpen(!open)} style={{
        background:'none', border:'none', color:'var(--primary)', fontSize:12,
        fontWeight:600, cursor:'pointer', padding:0, fontFamily:'inherit',
        display:'flex', alignItems:'center', gap:4
      }}>
        {open ? 'Hide' : (isSoft ? 'Why this matters?' : 'Why learn this?')}
        <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"
          style={{ transform: open ? 'rotate(180deg)' : 'none', transition:'transform 0.15s' }}>
          <polyline points="6 9 12 15 18 9"/>
        </svg>
      </button>
      {open && (
        <div style={{ marginTop:10 }}>
          <FormattedText text={item.reason} fontSize={12.5} />
        </div>
      )}
    </div>
  );
}
